### ISSUE TITLE
"No JSON object could be decoded" in terminal

### ISSUE THREAD

**Issue by selfcontrolla** [andreasgrill/auto-selfcontrol#10]
Hi I did follow how to set it up but when im at the stage "Execute sudo python auto-selfcontrol.py to install Auto-SelfControl with the block-schedule defined in config.json."

it says 

The json config file /Users/Jonte/Desktop/JONTE/autoselfcontrol/auto-selfcontrol-master/config.json is not correctly formatted.The following exception was raised:
No JSON object could be decoded

"{
    "username": ”Jonte”,
    "selfcontrol-path": "/Applications/SelfControl.app",
    "host-blacklist": [
        "reddit.com",
        "youtube.com"
    ],
    "block-schedules":[
        {
            "start-hour": 8,
            "start-minute": 0,
            "end-hour": 8,
            "end-minute": 10,
            "block-as-whitelist":true
        }
    ]
}"

Thank you.

**Comment by andreasgrill** [comment]
Hi!
There seems to be a problem with your config file. Are the quotation marks around your configuration included in the config file? Because they shouldn't. The following listing shows how your configuration should look like:

```
{
    "username": "Jonte",
    "selfcontrol-path": "/Applications/SelfControl.app",
    "host-blacklist": [
        "reddit.com",
        "youtube.com"
    ],
    "block-schedules":[
        {
            "start-hour": 8,
            "start-minute": 0,
            "end-hour": 8,
            "end-minute": 10,
            "block-as-whitelist":true
        }
    ]
}
```

Please also note, that this configuration uses the whitelist blocking approach, which in this case means that you are only allowed to visit reddit and youtube. I'm not sure if this is the behavior you have expected. If you want to use the blacklist filtering just change the `true` value of the _block-as-whitelist_ setting to `false`.
If you still have problems with the configuration format, have a look at an online json-tester, such as: http://jsoneditoronline.org, which could help you with syntax errors in your config.json file.

If you have any other problem, please let me know.
Cheers,
Andreas

**Comment by selfcontrolla** [comment]
Ah now it's working, what i did was removed the "reddit.com","youtube.com" under the blacklist. I do wan't blacklist just forgot to remove those. 

Is it set now so it start everyday with the code i pasted above? I set the time from 8 in the morning to 17.00 in the evening, it didnt start self control but it maybe doesn't start until I wait to the next day?


And again thank you for taking the time to do this, much appreciated!

**Comment by andreasgrill** [comment]
Thanks :)
I think the problem was that you used a text-editor that automatically inserted special quotation marks (the fancy ones ” instead of ") that broke the config file. If you change the config file in the future, I'd recommend to use a better suited text editor such as sublime, brackets, textmate or textwrangler. Anyone of these should do. 
Auto-SelfControl will automatically start tomorrow or simply when you restart your mac. However, just before I've read your post, I've updated Auto-SelfControl to automatically start after installation. So you could also just re-download auto-selfcontrol.py and execute the installation again, then it should start right away :)

**Comment by selfcontrolla** [comment]
Ah what a timing on that update, by the way yes I did a little mistake on using blacklist i though in reverse. I want so its whitelist how do I do that? And is it possible so you can't access internet on everything except the skype application on mac?

Thanks

**Comment by andreasgrill** [comment]
The blocklist or whitelist works by specifying domain names or IP-Addresses. To whitelist skype, you need to find out which domains or IP addresses skype needs. The problem is that skype probably uses direct communication with the other skype users and you would need to know the IP addresses of all the users. This could make it impossible to whitelist all required ip addresses. So I'm not sure whether it is possible to whitelist skype. Someone already asked this question on a [SelfControl page](https://github.com/SelfControlApp/selfcontrol/issues/240), you could try the suggested approach to find out what hosts should be whitelisted and could try it.

**Comment by selfcontrolla** [comment]
Ok got you, sorry for bugging you for long time but just one last question. I can't seem to get whitelist working, it always goes to blacklist mode

I simply want so when selfcontrol is active you cant access any sites or internet whatsoever.
this is my code can you spot where i did wrong?, thanks again :D:

{
    "username": "Jonte",
    "selfcontrol-path": "/Applications/SelfControl.app",
    "host-blacklist": [

    ],
    "block-schedules":[
        {
            "start-hour": 8,
            "start-minute": 0,
            "end-hour": 16,
            "end-minute": 0,
            "block-as-whitelist":true
        }
    ]
}

**Comment by andreasgrill** [comment]
Hmm...the configuration looks fine, but I must admit I haven't tested whitelisting without specifying a single host. You could try to add an unimportant host and execute the script again (I'm assuming you are using the current version now). If this still doesn't work then just let me know and I'll have a look at it by my self later tonight.

**Comment by selfcontrolla** [comment]
Ah yes that did it, just put in a random domain in the host-blacklist brackets, and it worked as whitelist.

Thanks alot for your coding and your help, have a nice day.

**Comment by andreasgrill** [comment]
I'm glad it works!
Cheers :)
