### ISSUE TITLE
Scheduling for 30 mins 'from now'

### ISSUE THREAD

**Issue by WillSen** [andreasgrill/auto-selfcontrol#11]
First - absolutely awesome that you created this - thanks Andreas

I want to be able to schedule for Selfcontrol to kick in 30 mins from now - short-term myopia means it's easier to commit to the app activating in the future than now

I'm happy to fork and work on the change, but I'm wondering if you had plans to work on this or had a workaround with the existing code

**Comment by andreasgrill** [comment]
Hi, thanks and I'm glad that you like it!

I think this is a great idea and I'd be happy to merge it back if you create a pull request. 

I don't have something like this planned. The next thing I'd like to address is a GUI because there are quite a lot of people who have trouble with the JSON-based configuration.

If you have any problem with the implementation or want to ask for help just let me know.

Cheers,
Andreas

**Comment by WillSen** [comment]
Sweet - will do so thanks Andreas
