### ISSUE TITLE
Allowed sites

### ISSUE THREAD

**Issue by Luigistudent** [andreasgrill/auto-selfcontrol#6]
If I want to add a new site to the whitelist while selfcontrol is running, is it as easy as changing the config.json?

**Comment by andreasgrill** [comment]
If you had a blacklist instead of a whitelist, you could start SelfControl add the new blacklisted sites to the currently running ones and then adding them in the config.json for future schedules. 
But I don't think SelfControl allows that for whitelists, because you'd limit its blocking behavior while being active.

**Comment by Luigistudent** [comment]
ok thanks!
