### ISSUE TITLE
Whitelist doesnt work

### ISSUE THREAD

**Issue by DavidvdBergh** [andreasgrill/auto-selfcontrol#8]
Hi Andreasgrill, I would greatly appreciate an explanation on how to make whitelisting properly work. I tried the ''whitelist..: true, but that didn't do it for me. Thanx ahead

**Comment by andreasgrill** [comment]
Hi!
It should work with this minimal config:
`{
    "username": "username",
    "selfcontrol-path": "/Applications/SelfControl.app",
    "host-blacklist": [
        "reddit.com",
        "youtube.com"
    ],
    "block-schedules":[
        {
            "start-hour": 8,
            "start-minute": 0,
            "end-hour": 8,
            "end-minute": 10,
            "block-as-whitelist":true
        }
    ]
}`

The "host-blacklist" setting is now used as a whitelist.
The "block-as-whitelist" setting needs to be defined in the block-schedules. This is a remnant of an early implementation of auto-selfcontrol that allows it to define blacklist or whitelist blocking (with custom lists) on a schedule basis. This still works but was removed from the readme since it is a feature that most users don't need. However, I'm planning on creating an "advanced" config section where I include the full configuration possibilities. A configuration GUI is also planned, but at the moment I don't have a lot free time :/

Let me know, if you need something else or if it's still not working with this config file.
Cheers,
Andreas

**Comment by DavidvdBergh** [comment]
AndreasGrill, this seemed to do it for me, don't really know what i did wrong last time. I literally can't thank you enough for helping me, means a lot to me. Been trying to find an automating Selfcontrol-app for months seriously, so making this work was a big relief for me. Cheers, David

**Comment by andreasgrill** [comment]
Good to hear that it works now :)
Cheers, 
Andreas

**Comment by su-narthur** [comment]
@andreasgrill Does this mean I could tell it to use a different list of sites for each scheduled period? how would that work?

**Comment by pooyaGames** [comment]
Worth to have this in First page.
